// 4clique Karnataka State-Wide Drainage & Rajakaluve Geospatial Database
// Multi-Resolution Spatial Indexing & Telemetry Configuration

export const KARNATAKA_DRAINS = [
  // ==========================================
  // 1. BENGALURU URBAN & BBMP (24 Major Trunks & Outfalls)
  // ==========================================
  {
    id: "drain_kc_valley",
    name: "Koramangala-Challaghatta Valley Primary Rajakaluve",
    shortName: "K&C Valley Rajakaluve",
    district: "Bengaluru Urban",
    taluk: "Bengaluru South",
    valley: "K&C Valley",
    type: "primary_rajakaluve",
    coordinates: [77.6245, 12.9352],
    defaultStatus: "Severe",
    designCapacityM3s: 180,
    currentDischargeM3s: 245,
    deficitPercent: 36,
    criticality: "High Risk - Chronic Backflow Hazard",
    description: "Primary stormwater trunk carrying municipal runoff towards Bellandur Lake. Heavily narrowed by encroachments; causes chronic backflow into Koramangala 4th Block and Ejipura.",
    lastDesilted: "2024-03-12"
  },
  {
    id: "drain_hebbal_valley",
    name: "Hebbal Valley Primary Trunk Drain",
    shortName: "Hebbal Valley Trunk Drain",
    district: "Bengaluru Urban",
    taluk: "Bengaluru North",
    valley: "Hebbal Valley",
    type: "primary_rajakaluve",
    coordinates: [77.5970, 13.0358],
    defaultStatus: "Moderate",
    designCapacityM3s: 120,
    currentDischargeM3s: 115,
    deficitPercent: 0,
    criticality: "Moderate Deficit - Near Capacity",
    description: "Key secondary rajakaluve draining north Bengaluru into Nagawara Lake. Silt deposition near the arterial flyover underpass reduces peak storm velocity.",
    lastDesilted: "2024-05-18"
  },
  {
    id: "drain_vrishabhavathi_silkboard",
    name: "Vrishabhavathi Valley / Silk Board Choke Corridor",
    shortName: "Silk Board - Madiwala Outfall",
    district: "Bengaluru Urban",
    taluk: "Bengaluru South",
    valley: "Vrishabhavathi Valley",
    type: "major_outfall",
    coordinates: [77.6227, 12.9172],
    defaultStatus: "Severe",
    designCapacityM3s: 150,
    currentDischargeM3s: 210,
    deficitPercent: 40,
    criticality: "Critical Deficit - Traffic Artery Gridlock",
    description: "Major confluence point between Madiwala lake overflow and arterial highway culverts. Regular severe flash ponding submerging service roads.",
    lastDesilted: "2024-02-28"
  },
  {
    id: "drain_mahadevapura_orr",
    name: "Mahadevapura / Outer Ring Road Tech Corridor Drain",
    shortName: "ORR Tech Corridor Rajakaluve",
    district: "Bengaluru Urban",
    taluk: "Mahadevapura",
    valley: "K&C Valley Outfall to Varthur",
    type: "primary_rajakaluve",
    coordinates: [77.7011, 12.9866],
    defaultStatus: "Moderate",
    designCapacityM3s: 95,
    currentDischargeM3s: 90,
    deficitPercent: 0,
    criticality: "Moderate Deficit - High Economic Vulnerability",
    description: "Crucial stormwater artery handling runoff from tech parks along ORR. Submergence of service roads cuts off access to over 100,000 workforce members.",
    lastDesilted: "2024-04-10"
  },
  {
    id: "drain_sankey_malleswaram",
    name: "Malleshwaram / Sankey Choke Line",
    shortName: "Sankey Tank Overflow Drain",
    district: "Bengaluru Urban",
    taluk: "Bengaluru North",
    valley: "Hebbal Sub-Catchment",
    type: "secondary_inlet",
    coordinates: [77.5709, 13.0088],
    defaultStatus: "Operational",
    designCapacityM3s: 45,
    currentDischargeM3s: 28,
    deficitPercent: 0,
    criticality: "Operational - Adequate Runoff Handling",
    description: "Masonry-lined drainage channel with recent desilting. Adequate capacity during seasonal monsoons with smooth gradient towards downstream tanks.",
    lastDesilted: "2024-06-02"
  },
  {
    id: "drain_hsr_sector6",
    name: "HSR Layout Sector 6 Main Outfall",
    shortName: "HSR Sector 6 Inter-Link Drain",
    district: "Bengaluru Urban",
    taluk: "Bommanahalli",
    valley: "Agara-Bellandur Inter-Link",
    type: "culvert_chokepoint",
    coordinates: [77.6389, 12.9116],
    defaultStatus: "Severe",
    designCapacityM3s: 60,
    currentDischargeM3s: 88,
    deficitPercent: 46,
    criticality: "Severe Backflow - Residential Risk",
    description: "Depression basin culvert susceptible to backflow from Agara lake during sustained heavy precipitation. Frequent basement parking inundation.",
    lastDesilted: "2024-01-15"
  },
  {
    id: "drain_indiranagar_100ft",
    name: "Indiranagar 100ft Road Secondary Outfall",
    shortName: "Indiranagar 100ft Road Secondary",
    district: "Bengaluru Urban",
    taluk: "Bengaluru East",
    valley: "K&C Valley Secondary",
    type: "secondary_inlet",
    coordinates: [77.6408, 12.9784],
    defaultStatus: "Operational",
    designCapacityM3s: 35,
    currentDischargeM3s: 22,
    deficitPercent: 0,
    criticality: "Operational - Normal Flow",
    description: "Recently remodeled box drain with automated silt screens. Free-flowing connection to downstream intermediate rajakaluve.",
    lastDesilted: "2024-05-29"
  },
  {
    id: "drain_bellandur_inlet_a",
    name: "Bellandur Wetland Western Trunk Inlet",
    shortName: "Bellandur West Inlet",
    district: "Bengaluru Urban",
    taluk: "Mahadevapura",
    valley: "Bellandur Basin",
    type: "major_outfall",
    coordinates: [77.6690, 12.9310],
    defaultStatus: "Severe",
    designCapacityM3s: 140,
    currentDischargeM3s: 175,
    deficitPercent: 25,
    criticality: "Severe Siltation & Foam Discharge",
    description: "Major confluence carrying storm runoffs from Ejipura and Koramangala into Bellandur Lake. Debris chokes reduce effective hydraulic cross-section.",
    lastDesilted: "2024-02-10"
  },
  {
    id: "drain_varthur_sluice",
    name: "Varthur Lake Emergency Overflow Sluice",
    shortName: "Varthur Lake Spillway",
    district: "Bengaluru Urban",
    taluk: "Mahadevapura",
    valley: "Dakshina Pinakini Basin",
    type: "major_outfall",
    coordinates: [77.7410, 12.9430],
    defaultStatus: "Moderate",
    designCapacityM3s: 220,
    currentDischargeM3s: 205,
    deficitPercent: 0,
    criticality: "Near Capacity - Downstream Flood Risk",
    description: "Terminal rajakaluve discharging eastern Bengaluru waters into Dakshina Pinakini river network. Regulates high monsoon discharges.",
    lastDesilted: "2024-04-20"
  },
  {
    id: "drain_kr_puram_tin_factory",
    name: "KR Puram / Tin Factory Arterial Storm Culvert",
    shortName: "Tin Factory Storm Culvert",
    district: "Bengaluru Urban",
    taluk: "Mahadevapura",
    valley: "K&C Valley Northern Tributary",
    type: "culvert_chokepoint",
    coordinates: [77.6790, 13.0040],
    defaultStatus: "Severe",
    designCapacityM3s: 55,
    currentDischargeM3s: 82,
    deficitPercent: 49,
    criticality: "Critical Deficit - Highway Submersion",
    description: "Old railway bridge culvert with high siltation causing recurring highway inundation at Tin Factory junction under monsoon rain.",
    lastDesilted: "2023-11-14"
  },
  {
    id: "drain_nagawara_manyata",
    name: "Nagawara Lake Inflow & Manyata Tech Park Bypass",
    shortName: "Manyata - Nagawara Bypass",
    district: "Bengaluru Urban",
    taluk: "Bengaluru North",
    valley: "Hebbal-Nagawara Basin",
    type: "primary_rajakaluve",
    coordinates: [77.6210, 13.0480],
    defaultStatus: "Moderate",
    designCapacityM3s: 85,
    currentDischargeM3s: 82,
    deficitPercent: 0,
    criticality: "High Commercial Exposure",
    description: "Box culvert channel carrying north city flood runoff. Vulnerable to ingress into IT park perimeter during intense cloudbursts.",
    lastDesilted: "2024-05-02"
  },
  {
    id: "drain_yelahanka_kogilu",
    name: "Yelahanka Kogilu Road Drainage Confluence",
    shortName: "Yelahanka Kogilu Drain",
    district: "Bengaluru Urban",
    taluk: "Yelahanka",
    valley: "Yelahanka Lake Basin",
    type: "primary_rajakaluve",
    coordinates: [77.5990, 13.1080],
    defaultStatus: "Severe",
    designCapacityM3s: 65,
    currentDischargeM3s: 92,
    deficitPercent: 41,
    criticality: "Severe Overtopping - Kendriya Vihar Risk",
    description: "Stormwater collector draining residential layouts into Yelahanka Lake. Subject to backflow inundation when lake level reaches full reservoir capacity.",
    lastDesilted: "2024-03-01"
  },
  {
    id: "drain_peenya_2nd_stage",
    name: "Peenya Industrial Area Stage 2 Collector Nala",
    shortName: "Peenya Industrial Collector",
    district: "Bengaluru Urban",
    taluk: "Bengaluru North",
    valley: "Vrishabhavathi Northern Headwaters",
    type: "primary_rajakaluve",
    coordinates: [77.5140, 13.0290],
    defaultStatus: "Moderate",
    designCapacityM3s: 70,
    currentDischargeM3s: 64,
    deficitPercent: 0,
    criticality: "Industrial Effluent Confluence",
    description: "Concrete canal handling industrial estate stormwater runoff towards Vrishabhavathi basin.",
    lastDesilted: "2024-06-11"
  },
  {
    id: "drain_kengeri_mori",
    name: "Kengeri Mori / Vrishabhavathi Primary Discharge",
    shortName: "Kengeri Mori Rajakaluve",
    district: "Bengaluru Urban",
    taluk: "Rajarajeshwari Nagar",
    valley: "Vrishabhavathi Main Stem",
    type: "major_outfall",
    coordinates: [77.4820, 12.9110],
    defaultStatus: "Operational",
    designCapacityM3s: 210,
    currentDischargeM3s: 160,
    deficitPercent: 0,
    criticality: "Operational - High Discharge Trunk",
    description: "Wide natural river-turned-storm trunk flowing southwest. Well-maintained embankment with strong gradient.",
    lastDesilted: "2024-05-15"
  },
  {
    id: "drain_electronic_city_phase1",
    name: "Electronic City Phase 1 Main Nala Outfall",
    shortName: "Electronic City Phase 1 Nala",
    district: "Bengaluru Urban",
    taluk: "Anekal",
    valley: "Hebbagodi Lake Catchment",
    type: "primary_rajakaluve",
    coordinates: [77.6740, 12.8480],
    defaultStatus: "Operational",
    designCapacityM3s: 50,
    currentDischargeM3s: 32,
    deficitPercent: 0,
    criticality: "Operational - Regulated Flow",
    description: "Upgraded trapezoidal concrete storm nala draining IT campuses towards downstream irrigation tanks.",
    lastDesilted: "2024-04-18"
  },
  {
    id: "drain_whitefield_kadugodi",
    name: "Whitefield Kadugodi Main Secondary Storm Nala",
    shortName: "Kadugodi Secondary Drain",
    district: "Bengaluru Urban",
    taluk: "Mahadevapura",
    valley: "K&C Valley Eastern Sub-Basin",
    type: "secondary_inlet",
    coordinates: [77.7560, 12.9920],
    defaultStatus: "Moderate",
    designCapacityM3s: 48,
    currentDischargeM3s: 44,
    deficitPercent: 0,
    criticality: "Moderate Silt Load",
    description: "Rapidly urbanized corridor drain handling commuter railway underpass and tech corridors.",
    lastDesilted: "2024-03-30"
  },

  // ==========================================
  // 2. BENGALURU RURAL & RAMANAGARA (5 Trunks)
  // ==========================================
  {
    id: "drain_ramanagara_arkavathi",
    name: "Ramanagara Arkavathi River Confluence Outfall",
    shortName: "Ramanagara Arkavathi Outfall",
    district: "Ramanagara",
    taluk: "Ramanagara",
    valley: "Arkavathi Basin",
    type: "major_outfall",
    coordinates: [77.2780, 12.7230],
    defaultStatus: "Operational",
    designCapacityM3s: 130,
    currentDischargeM3s: 75,
    deficitPercent: 0,
    criticality: "Operational - Natural River Inflow",
    description: "Main municipal stormwater outfall discharging treated and storm runoff into Arkavathi riverbed.",
    lastDesilted: "2024-02-15"
  },
  {
    id: "drain_channapatna_kanva",
    name: "Channapatna Kanva Reservoir Feeder Channel",
    shortName: "Kanva Feeder Channel",
    district: "Ramanagara",
    taluk: "Channapatna",
    valley: "Kanva Basin",
    type: "primary_rajakaluve",
    coordinates: [77.2010, 12.6520],
    defaultStatus: "Operational",
    designCapacityM3s: 85,
    currentDischargeM3s: 48,
    deficitPercent: 0,
    criticality: "Operational - Irrigation Link",
    description: "Stone-pitched feeder channel transporting surplus runoff into Kanva Reservoir.",
    lastDesilted: "2024-05-10"
  },
  {
    id: "drain_doddaballapura_industrial",
    name: "Doddaballapura KIADB Industrial Drainage Nala",
    shortName: "Doddaballapura KIADB Nala",
    district: "Bengaluru Rural",
    taluk: "Doddaballapura",
    valley: "Pinakini Catchment",
    type: "primary_rajakaluve",
    coordinates: [77.5340, 13.2920],
    defaultStatus: "Moderate",
    designCapacityM3s: 60,
    currentDischargeM3s: 58,
    deficitPercent: 0,
    criticality: "Industrial Estate Ingress Watch",
    description: "Main collector channel for textile and engineering parks north of Bengaluru.",
    lastDesilted: "2024-04-05"
  },
  {
    id: "drain_nelamangala_culvert",
    name: "Nelamangala Highway Cross-Drainage Culvert",
    shortName: "Nelamangala NH48 Culvert",
    district: "Bengaluru Rural",
    taluk: "Nelamangala",
    valley: "Arkavathi Headwaters",
    type: "culvert_chokepoint",
    coordinates: [77.3890, 13.0980],
    defaultStatus: "Severe",
    designCapacityM3s: 55,
    currentDischargeM3s: 74,
    deficitPercent: 34,
    criticality: "Highway Truck Corridors Flood Hazard",
    description: "Key logistics highway culvert where debris deposition triggers backwater flash ponding across toll lanes.",
    lastDesilted: "2023-12-10"
  },
  {
    id: "drain_kanakapura_town_outfall",
    name: "Kanakapura Town Storm Outfall to Arkavathi",
    shortName: "Kanakapura Storm Outfall",
    district: "Ramanagara",
    taluk: "Kanakapura",
    valley: "Arkavathi Basin",
    type: "major_outfall",
    coordinates: [77.4180, 12.5480],
    defaultStatus: "Operational",
    designCapacityM3s: 70,
    currentDischargeM3s: 38,
    deficitPercent: 0,
    criticality: "Operational - Free Flow Gradient",
    description: "Steep-gradient gravity outfall providing smooth runoff disposal into Arkavathi riverbed.",
    lastDesilted: "2024-06-01"
  },

  // ==========================================
  // 3. MYSURU & MANDYA (CAUVERY BASIN) (6 Trunks)
  // ==========================================
  {
    id: "drain_mysuru_kukkarahalli",
    name: "Kukkarahalli Lake Overflow Primary Nala",
    shortName: "Kukkarahalli Lake Outflow",
    district: "Mysuru",
    taluk: "Mysuru",
    valley: "Cauvery Sub-Catchment",
    type: "primary_rajakaluve",
    coordinates: [76.6310, 12.3120],
    defaultStatus: "Moderate",
    designCapacityM3s: 80,
    currentDischargeM3s: 72,
    deficitPercent: 0,
    criticality: "Heritage Zone Lake Link",
    description: "Carries university and central Mysuru overflow towards Dalvoi Lake. Heavy vegetation growth periodically restricts cross-sectional flow.",
    lastDesilted: "2024-04-12"
  },
  {
    id: "drain_mysuru_lingambudhi",
    name: "Lingambudhi Lake Storm Canal Outfall",
    shortName: "Lingambudhi Canal Outfall",
    district: "Mysuru",
    taluk: "Mysuru",
    valley: "Kabini Tributary Basin",
    type: "major_outfall",
    coordinates: [76.6210, 12.2780],
    defaultStatus: "Operational",
    designCapacityM3s: 90,
    currentDischargeM3s: 52,
    deficitPercent: 0,
    criticality: "Operational - High Sluice Clearance",
    description: "Broad stone-pitched outflow canal discharging into south Mysuru wetland corridor.",
    lastDesilted: "2024-05-22"
  },
  {
    id: "drain_mysuru_suburban_busstand",
    name: "Mysuru City Suburban Bus Stand Lowland Sump Channel",
    shortName: "Mysuru Bus Stand Sump Nala",
    district: "Mysuru",
    taluk: "Mysuru",
    valley: "Mysuru Urban Core",
    type: "culvert_chokepoint",
    coordinates: [76.6540, 12.3080],
    defaultStatus: "Severe",
    designCapacityM3s: 40,
    currentDischargeM3s: 58,
    deficitPercent: 45,
    criticality: "Severe Waterlogging - Transit Hub Ingress",
    description: "Natural depression basin near Suburban bus terminal. Choked inlets cause flash parking and bus bay flooding during 50+ mm storms.",
    lastDesilted: "2024-01-20"
  },
  {
    id: "drain_mandya_main_storm",
    name: "Mandya City Main Stormwater Corridor",
    shortName: "Mandya City Central Nala",
    district: "Mandya",
    taluk: "Mandya",
    valley: "Shimsha River Sub-Basin",
    type: "primary_rajakaluve",
    coordinates: [76.8960, 12.5240],
    defaultStatus: "Moderate",
    designCapacityM3s: 65,
    currentDischargeM3s: 60,
    deficitPercent: 0,
    criticality: "Railway Underpass Choke Risk",
    description: "Central rajakaluve cutting through sugar factory zone. Railway culvert narrows flow creating temporary backflow.",
    lastDesilted: "2024-03-15"
  },
  {
    id: "drain_srirangapatna_cauvery",
    name: "Srirangapatna Paschimavahini Cauvery River Outfall",
    shortName: "Srirangapatna Cauvery Outfall",
    district: "Mandya",
    taluk: "Srirangapatna",
    valley: "Cauvery Main Stem",
    type: "major_outfall",
    coordinates: [76.6850, 12.4210],
    defaultStatus: "Operational",
    designCapacityM3s: 160,
    currentDischargeM3s: 90,
    deficitPercent: 0,
    criticality: "Operational - Natural River Discharge",
    description: "Island town primary drainage sluice flowing directly into Cauvery north branch.",
    lastDesilted: "2024-05-30"
  },
  {
    id: "drain_maddur_shimsha",
    name: "Maddur Shimsha River Discharge Canal",
    shortName: "Maddur Shimsha Canal",
    district: "Mandya",
    taluk: "Maddur",
    valley: "Shimsha Basin",
    type: "major_outfall",
    coordinates: [77.0450, 12.5840],
    defaultStatus: "Operational",
    designCapacityM3s: 110,
    currentDischargeM3s: 65,
    deficitPercent: 0,
    criticality: "Operational - Broad Basin Outlet",
    description: "Natural deep ravine discharging urban runoff safely into Shimsha riverbed.",
    lastDesilted: "2024-04-10"
  },

  // ==========================================
  // 4. DAKSHINA KANNADA & UDUPI (COASTAL BELT) (7 Trunks)
  // ==========================================
  {
    id: "drain_mangaluru_bunder",
    name: "Mangaluru Old Port / Bunder Tidal Storm Drain",
    shortName: "Bunder Tidal Outfall",
    district: "Dakshina Kannada",
    taluk: "Mangaluru",
    valley: "Gurupura-Netravati Estuary",
    type: "major_outfall",
    coordinates: [74.8390, 12.8620],
    defaultStatus: "Severe",
    designCapacityM3s: 140,
    currentDischargeM3s: 195,
    deficitPercent: 39,
    criticality: "High Tidal Inundation & Sea Backflow Risk",
    description: "Critical maritime drain. High tide confluence with intense coastal monsoons (>100mm/d) causes severe sea water backflow into commercial markets.",
    lastDesilted: "2024-05-14"
  },
  {
    id: "drain_mangaluru_kottara_chowki",
    name: "Kottara Chowki Highway Underpass Storm Culvert",
    shortName: "Kottara Chowki Culvert",
    district: "Dakshina Kannada",
    taluk: "Mangaluru",
    valley: "Kuloor Storm Basin",
    type: "culvert_chokepoint",
    coordinates: [74.8380, 12.9020],
    defaultStatus: "Severe",
    designCapacityM3s: 85,
    currentDischargeM3s: 125,
    deficitPercent: 47,
    criticality: "Severe Highway Arterial Inundation",
    description: "Chronic flash-flooding hotspot on NH66. Silt and low gradient trap runoff submerging underpass up to 1.5 meters during high monsoon spells.",
    lastDesilted: "2024-03-25"
  },
  {
    id: "drain_mangaluru_pumpwell",
    name: "Pumpwell Junction Lowland Storm Collector",
    shortName: "Pumpwell Storm Basin",
    district: "Dakshina Kannada",
    taluk: "Mangaluru",
    valley: "Netravati Catchment",
    type: "primary_rajakaluve",
    coordinates: [74.8680, 12.8590],
    defaultStatus: "Moderate",
    designCapacityM3s: 95,
    currentDischargeM3s: 90,
    deficitPercent: 0,
    criticality: "Transit Corridor Vulnerability",
    description: "Engineered box drains installed around Pumpwell flyover; moderate siltation near culvert mouth requires active desilting.",
    lastDesilted: "2024-05-18"
  },
  {
    id: "drain_udupi_indrali",
    name: "Udupi City Indrali Nala Primary Storm Corridor",
    shortName: "Udupi Indrali Nala",
    district: "Udupi",
    taluk: "Udupi",
    valley: "Udyavara River Basin",
    type: "primary_rajakaluve",
    coordinates: [74.7560, 13.3420],
    defaultStatus: "Moderate",
    designCapacityM3s: 90,
    currentDischargeM3s: 85,
    deficitPercent: 0,
    criticality: "City Core Drainage Arterial",
    description: "Primary municipal canal connecting Manipal ridge down to Udupi city lowlands. Rapid runoff velocity during torrential rain.",
    lastDesilted: "2024-04-28"
  },
  {
    id: "drain_malpe_harbour",
    name: "Malpe Harbour Coastal Storm Bypass",
    shortName: "Malpe Harbour Bypass",
    district: "Udupi",
    taluk: "Udupi",
    valley: "Arabian Sea Coastal Basin",
    type: "major_outfall",
    coordinates: [74.7020, 13.3510],
    defaultStatus: "Operational",
    designCapacityM3s: 110,
    currentDischargeM3s: 65,
    deficitPercent: 0,
    criticality: "Operational - Direct Ocean Sluice",
    description: "Twin box culverts delivering fisheries complex and city runoff smoothly into harbour backwaters.",
    lastDesilted: "2024-06-05"
  },
  {
    id: "drain_surathkal_coastal",
    name: "Surathkal NITK Coastal Storm Chokepoint",
    shortName: "Surathkal Coastal Culvert",
    district: "Dakshina Kannada",
    taluk: "Mangaluru",
    valley: "Pavanje Estuary Link",
    type: "culvert_chokepoint",
    coordinates: [74.7920, 13.0110],
    defaultStatus: "Moderate",
    designCapacityM3s: 60,
    currentDischargeM3s: 55,
    deficitPercent: 0,
    criticality: "Sand Bar Beach Siltation",
    description: "Discharges beach runoff; littoral drift causes sandbar blocking at mouth during southwest monsoons.",
    lastDesilted: "2024-05-12"
  },
  {
    id: "drain_kundapura_panchagangavali",
    name: "Kundapura Panchagangavali Estuary Outfall",
    shortName: "Panchagangavali Estuary Outfall",
    district: "Udupi",
    taluk: "Kundapura",
    valley: "Panchagangavali Estuary",
    type: "major_outfall",
    coordinates: [74.6930, 13.6280],
    defaultStatus: "Operational",
    designCapacityM3s: 180,
    currentDischargeM3s: 110,
    deficitPercent: 0,
    criticality: "Operational - Broad Estuarine Confluence",
    description: "Multi-river estuarine confluence drain with high hydraulic capacity.",
    lastDesilted: "2024-05-20"
  },

  // ==========================================
  // 5. UTTARA KANNADA (4 Trunks)
  // ==========================================
  {
    id: "drain_karwar_kali",
    name: "Karwar Kali River Estuary Urban Storm Channel",
    shortName: "Karwar Kali Channel",
    district: "Uttara Kannada",
    taluk: "Karwar",
    valley: "Kali River Estuary",
    type: "major_outfall",
    coordinates: [74.1350, 14.8180],
    defaultStatus: "Moderate",
    designCapacityM3s: 120,
    currentDischargeM3s: 105,
    deficitPercent: 0,
    criticality: "Coastal Defense Confluence",
    description: "Main storm artery for Karwar port and naval base perimeter discharging into Kali river mouth.",
    lastDesilted: "2024-04-18"
  },
  {
    id: "drain_bhatkal_sharabi",
    name: "Bhatkal Sharabi Stream Coastal Flood Basin",
    shortName: "Bhatkal Sharabi Basin",
    district: "Uttara Kannada",
    taluk: "Bhatkal",
    valley: "Sharabi Basin",
    type: "primary_rajakaluve",
    coordinates: [74.5510, 13.9770],
    defaultStatus: "Severe",
    designCapacityM3s: 85,
    currentDischargeM3s: 120,
    deficitPercent: 41,
    criticality: "Severe Flash Inundation Risk",
    description: "Steep coastal catchment torrent funneling high rainfall into narrow urban market channels; chronic flash flooding hazard.",
    lastDesilted: "2024-02-22"
  },
  {
    id: "drain_kumta_aghnashini",
    name: "Kumta Aghnashini Tidal Backflow Drain",
    shortName: "Kumta Aghnashini Sluice",
    district: "Uttara Kannada",
    taluk: "Kumta",
    valley: "Aghnashini Estuary",
    type: "major_outfall",
    coordinates: [74.4210, 14.4260],
    defaultStatus: "Operational",
    designCapacityM3s: 95,
    currentDischargeM3s: 58,
    deficitPercent: 0,
    criticality: "Operational - Tidal Gates Active",
    description: "Fitted with automated non-return tidal flap gates to prevent saline backflow.",
    lastDesilted: "2024-05-16"
  },
  {
    id: "drain_sirsi_hill_slope",
    name: "Sirsi Town Hill-Slope Stormwater Cascades",
    shortName: "Sirsi Hill Cascades",
    district: "Uttara Kannada",
    taluk: "Sirsi",
    valley: "Aghanashini Headwaters",
    type: "primary_rajakaluve",
    coordinates: [74.8540, 14.6190],
    defaultStatus: "Operational",
    designCapacityM3s: 75,
    currentDischargeM3s: 42,
    deficitPercent: 0,
    criticality: "High Gradient Gravity Runoff",
    description: "Western Ghats ridgeline storm cascades with stepped masonry energy dissipators.",
    lastDesilted: "2024-05-28"
  },

  // ==========================================
  // 6. BELAGAVI & HUBBALLI-DHARWAD (6 Trunks)
  // ==========================================
  {
    id: "drain_belagavi_bellary_nala",
    name: "Belagavi Bellary Nala Main Flood Arterial",
    shortName: "Bellary Nala Belagavi",
    district: "Belagavi",
    taluk: "Belagavi",
    valley: "Markandeya-Ghataprabha Basin",
    type: "primary_rajakaluve",
    coordinates: [74.5210, 15.8560],
    defaultStatus: "Severe",
    designCapacityM3s: 160,
    currentDischargeM3s: 220,
    deficitPercent: 37,
    criticality: "Severe City Basin Inundation Hazard",
    description: "Notorious urban flood channel collecting over 70% of Belagavi city storm runoffs. Silt and debris cause backflow submerging low-lying residential sectors.",
    lastDesilted: "2024-01-28"
  },
  {
    id: "drain_hubballi_unkal",
    name: "Hubballi Unkal Lake Main Overflow Canal",
    shortName: "Unkal Lake Overflow Canal",
    district: "Dharwad",
    taluk: "Hubballi",
    valley: "Malaprabha Sub-Catchment",
    type: "primary_rajakaluve",
    coordinates: [75.1120, 15.3780],
    defaultStatus: "Moderate",
    designCapacityM3s: 85,
    currentDischargeM3s: 78,
    deficitPercent: 0,
    criticality: "Twin-City Drainage Link",
    description: "Connects Unkal Lake overflow downstream towards Gabbur agricultural belt. Silt accumulation at culverts requires regular clearing.",
    lastDesilted: "2024-04-14"
  },
  {
    id: "drain_hubballi_gabbur",
    name: "Hubballi Gabbur Nala Highway Cross-Drain",
    shortName: "Gabbur Highway Nala",
    district: "Dharwad",
    taluk: "Hubballi",
    valley: "Bennihalla Basin",
    type: "culvert_chokepoint",
    coordinates: [75.1480, 15.3340],
    defaultStatus: "Severe",
    designCapacityM3s: 70,
    currentDischargeM3s: 98,
    deficitPercent: 40,
    criticality: "Critical Deficit - Highway Traffic Choke",
    description: "Major confluence where city southern nala meets National Highway underpass culverts; frequent heavy ponding.",
    lastDesilted: "2023-12-18"
  },
  {
    id: "drain_dharwad_kelgeri",
    name: "Dharwad Kelgeri Lake Main Outflow Canal",
    shortName: "Kelgeri Outflow Canal",
    district: "Dharwad",
    taluk: "Dharwad",
    valley: "Malaprabha Headwaters",
    type: "primary_rajakaluve",
    coordinates: [75.0080, 15.4610],
    defaultStatus: "Operational",
    designCapacityM3s: 65,
    currentDischargeM3s: 38,
    deficitPercent: 0,
    criticality: "Operational - Clear Sluice Capacity",
    description: "Masonry canal leading from Kelgeri Lake through agricultural bypass channels.",
    lastDesilted: "2024-05-19"
  },
  {
    id: "drain_dharwad_navalur",
    name: "Dharwad Navalur Industrial Storm Culvert",
    shortName: "Navalur Industrial Drain",
    district: "Dharwad",
    taluk: "Dharwad",
    valley: "Dharwad Industrial Belt",
    type: "secondary_inlet",
    coordinates: [75.0560, 15.4050],
    defaultStatus: "Operational",
    designCapacityM3s: 50,
    currentDischargeM3s: 32,
    deficitPercent: 0,
    criticality: "Operational - Adequate Capacity",
    description: "Servicing tech corridors and engineering plants along twin-city BRTS corridor.",
    lastDesilted: "2024-06-03"
  },
  {
    id: "drain_gokak_ghataprabha",
    name: "Gokak Falls Ghataprabha Torrent Discharge",
    shortName: "Gokak Ghataprabha Discharge",
    district: "Belagavi",
    taluk: "Gokak",
    valley: "Ghataprabha Main Stem",
    type: "major_outfall",
    coordinates: [74.8290, 16.1680],
    defaultStatus: "Operational",
    designCapacityM3s: 240,
    currentDischargeM3s: 130,
    deficitPercent: 0,
    criticality: "Operational - High Gorge Capacity",
    description: "Natural rocky gorge with immense flood discharging capacity into Ghataprabha river.",
    lastDesilted: "2024-05-01"
  },

  // ==========================================
  // 7. KALABURAGI, BIDAR, YADGIR & RAICHUR (KALYANA KARNATAKA) (5 Trunks)
  // ==========================================
  {
    id: "drain_kalaburagi_appa_tank",
    name: "Kalaburagi Appa Tank Primary Storm Drainage Trunk",
    shortName: "Appa Tank Storm Trunk",
    district: "Kalaburagi",
    taluk: "Kalaburagi",
    valley: "Bhima-Kangana Basin",
    type: "primary_rajakaluve",
    coordinates: [76.8320, 17.3310],
    defaultStatus: "Severe",
    designCapacityM3s: 75,
    currentDischargeM3s: 104,
    deficitPercent: 38,
    criticality: "Severe City Center Lowland Inundation",
    description: "Drains high-density old city areas into Sharanabasaveshwara lake network; blocked masonry culverts trigger street waterlogging.",
    lastDesilted: "2024-02-14"
  },
  {
    id: "drain_bidar_fort_moat",
    name: "Bidar Historical Moat Storm Interceptor Nala",
    shortName: "Bidar Fort Moat Nala",
    district: "Bidar",
    taluk: "Bidar",
    valley: "Manjra Basin",
    type: "primary_rajakaluve",
    coordinates: [77.5310, 17.9140],
    defaultStatus: "Operational",
    designCapacityM3s: 60,
    currentDischargeM3s: 34,
    deficitPercent: 0,
    criticality: "Operational - Ancient Gravity Siphon",
    description: "Ancient stepped aqueduct channels integrated into modern urban storm collector system.",
    lastDesilted: "2024-05-24"
  },
  {
    id: "drain_yadgir_bheema_outfall",
    name: "Yadgir City Bheema Basin Storm Outfall",
    shortName: "Yadgir Bheema Outfall",
    district: "Yadgir",
    taluk: "Yadgir",
    valley: "Bhima Basin",
    type: "major_outfall",
    coordinates: [77.1350, 16.7680],
    defaultStatus: "Moderate",
    designCapacityM3s: 70,
    currentDischargeM3s: 65,
    deficitPercent: 0,
    criticality: "River Backflow Vulnerability",
    description: "Discharges into Bhima river plain; high river stage during monsoon limits gravity outflow.",
    lastDesilted: "2024-03-19"
  },
  {
    id: "drain_raichur_station_road",
    name: "Raichur City Station Road Lowland Nala",
    shortName: "Raichur Station Nala",
    district: "Raichur",
    taluk: "Raichur",
    valley: "Krishna-Tungabhadra Doab",
    type: "culvert_chokepoint",
    coordinates: [77.3580, 16.2050],
    defaultStatus: "Moderate",
    designCapacityM3s: 55,
    currentDischargeM3s: 52,
    deficitPercent: 0,
    criticality: "Transit Corridor Sump",
    description: "Railway station road collector nala; prone to silt buildup from red soil erosion.",
    lastDesilted: "2024-04-11"
  },
  {
    id: "drain_kalaburagi_shahabad_road",
    name: "Kalaburagi Shahabad Road Highway Nala",
    shortName: "Shahabad Highway Nala",
    district: "Kalaburagi",
    taluk: "Kalaburagi",
    valley: "Bhima Basin Outfall",
    type: "secondary_inlet",
    coordinates: [76.8450, 17.3120],
    defaultStatus: "Operational",
    designCapacityM3s: 50,
    currentDischargeM3s: 28,
    deficitPercent: 0,
    criticality: "Operational - Normal Gradient",
    description: "Cement-lined roadside collector with open flow towards south outfall.",
    lastDesilted: "2024-05-09"
  },

  // ==========================================
  // 8. BALLARI, VIJAYANAGARA & CENTRAL KARNATAKA (6 Trunks)
  // ==========================================
  {
    id: "drain_ballari_fort_lowland",
    name: "Ballari Fort Low-Lying Ditch Storm Outfall",
    shortName: "Ballari Fort Nala",
    district: "Ballari",
    taluk: "Ballari",
    valley: "Hagari / Vedavati Basin",
    type: "culvert_chokepoint",
    coordinates: [76.9240, 15.1480],
    defaultStatus: "Moderate",
    designCapacityM3s: 65,
    currentDischargeM3s: 62,
    deficitPercent: 0,
    criticality: "Fort Basin Sump",
    description: "Collects city center runoffs around the granite rock hill; heavy rain causes ponding along market arteries.",
    lastDesilted: "2024-03-08"
  },
  {
    id: "drain_hosapete_tungabhadra",
    name: "Hosapete Tungabhadra High-Level Canal Bypass",
    shortName: "Hosapete TB Canal Bypass",
    district: "Vijayanagara",
    taluk: "Hosapete",
    valley: "Tungabhadra Basin",
    type: "major_outfall",
    coordinates: [76.3920, 15.2710],
    defaultStatus: "Operational",
    designCapacityM3s: 180,
    currentDischargeM3s: 95,
    deficitPercent: 0,
    criticality: "Operational - Engineered Escape Sluice",
    description: "Modern escape canal diverting surplus city stormwater away from UNESCO Hampi buffer zone.",
    lastDesilted: "2024-05-18"
  },
  {
    id: "drain_davanagere_bathi",
    name: "Davanagere Bathi Lake Industrial Storm Drain",
    shortName: "Davanagere Bathi Drain",
    district: "Davanagere",
    taluk: "Davanagere",
    valley: "Tungabhadra Valley",
    type: "primary_rajakaluve",
    coordinates: [75.9180, 14.4690],
    defaultStatus: "Moderate",
    designCapacityM3s: 70,
    currentDischargeM3s: 68,
    deficitPercent: 0,
    criticality: "Textile Belt Runoff",
    description: "Carries textile city storm runoff out to Bathi lake wetlands; weed clogging monitored.",
    lastDesilted: "2024-04-19"
  },
  {
    id: "drain_chitradurga_chandravalli",
    name: "Chitradurga Chandravalli Valley Storm Channel",
    shortName: "Chandravalli Storm Channel",
    district: "Chitradurga",
    taluk: "Chitradurga",
    valley: "Vedavati Basin",
    type: "primary_rajakaluve",
    coordinates: [76.4020, 14.2210],
    defaultStatus: "Operational",
    designCapacityM3s: 60,
    currentDischargeM3s: 32,
    deficitPercent: 0,
    criticality: "Operational - Stone Incline",
    description: "Historical cascade channels routing hill torrents smoothly around Chitradurga Fort.",
    lastDesilted: "2024-05-25"
  },
  {
    id: "drain_shivamogga_tunga",
    name: "Shivamogga Tunga River Front Primary Drain",
    shortName: "Shivamogga Tunga Drain",
    district: "Shivamogga",
    taluk: "Shivamogga",
    valley: "Tunga River Main Stem",
    type: "major_outfall",
    coordinates: [75.5720, 13.9310],
    defaultStatus: "Moderate",
    designCapacityM3s: 120,
    currentDischargeM3s: 110,
    deficitPercent: 0,
    criticality: "High Monsoon Inflow Exposure",
    description: "Direct outfall into Tunga river; during peak Malnad monsoons high river level impedes municipal discharge.",
    lastDesilted: "2024-04-30"
  },
  {
    id: "drain_bhadravati_canal",
    name: "Bhadravati Industrial Effluent & Storm Canal",
    shortName: "Bhadravati Industrial Canal",
    district: "Shivamogga",
    taluk: "Bhadravati",
    valley: "Bhadra Basin",
    type: "primary_rajakaluve",
    coordinates: [75.7110, 13.8420],
    defaultStatus: "Operational",
    designCapacityM3s: 80,
    currentDischargeM3s: 48,
    deficitPercent: 0,
    criticality: "Operational - Direct Bhadra Confluence",
    description: "Deep canal servicing paper and iron works with high capacity outlet to Bhadra river.",
    lastDesilted: "2024-05-12"
  },

  // ==========================================
  // 9. WESTERN GHATS & SOUTH-CENTRAL (5 Trunks)
  // ==========================================
  {
    id: "drain_madikeri_torrent",
    name: "Madikeri Valley Torrent High-Gradient Channel",
    shortName: "Madikeri Valley Torrent",
    district: "Kodagu",
    taluk: "Madikeri",
    valley: "Cauvery Headwaters",
    type: "primary_rajakaluve",
    coordinates: [75.7380, 12.4240],
    defaultStatus: "Severe",
    designCapacityM3s: 90,
    currentDischargeM3s: 135,
    deficitPercent: 50,
    criticality: "Severe Flash Debris & Landslip Confluence",
    description: "Extremely steep hillside stormwater torrent. Heavy mud and tree debris during intense Western Ghats downpours cause culvert chokes.",
    lastDesilted: "2024-03-05"
  },
  {
    id: "drain_hassan_channapatna_lake",
    name: "Hassan Channapatna Lake Outflow Canal",
    shortName: "Hassan Lake Canal",
    district: "Hassan",
    taluk: "Hassan",
    valley: "Hemavathi Sub-Catchment",
    type: "primary_rajakaluve",
    coordinates: [76.1020, 13.0080],
    defaultStatus: "Operational",
    designCapacityM3s: 75,
    currentDischargeM3s: 42,
    deficitPercent: 0,
    criticality: "Operational - Stable Capacity",
    description: "Spillway canal carrying Hassan municipal runoff into Hemavathi feeder network.",
    lastDesilted: "2024-05-10"
  },
  {
    id: "drain_chikkamagaluru_yagachi",
    name: "Chikkamagaluru Yagachi River Stream Feeders",
    shortName: "Yagachi Stream Feeder",
    district: "Chikkamagaluru",
    taluk: "Chikkamagaluru",
    valley: "Yagachi Basin",
    type: "primary_rajakaluve",
    coordinates: [75.7760, 13.3180],
    defaultStatus: "Operational",
    designCapacityM3s: 70,
    currentDischargeM3s: 36,
    deficitPercent: 0,
    criticality: "Operational - Natural Gradient",
    description: "Coffee estate hill drainage meeting city storm collector channel with stable flow.",
    lastDesilted: "2024-05-20"
  },
  {
    id: "drain_tumakuru_amanikere",
    name: "Tumakuru Amanikere Storm Spillway Canal",
    shortName: "Tumakuru Amanikere Spillway",
    district: "Tumakuru",
    taluk: "Tumakuru",
    valley: "Shimsha Headwaters",
    type: "major_outfall",
    coordinates: [77.1080, 13.3420],
    defaultStatus: "Moderate",
    designCapacityM3s: 85,
    currentDischargeM3s: 80,
    deficitPercent: 0,
    criticality: "Smart City Upgraded Sluice",
    description: "Renovated spillway channel connecting Amanikere to downstream tank cascade.",
    lastDesilted: "2024-04-25"
  },
  {
    id: "drain_kolar_chota_simla",
    name: "Kolar Chota Simla Lowland Storm Canal",
    shortName: "Kolar Simla Canal",
    district: "Kolar",
    taluk: "Kolar",
    valley: "Palar Catchment",
    type: "primary_rajakaluve",
    coordinates: [78.1320, 13.1360],
    defaultStatus: "Operational",
    designCapacityM3s: 55,
    currentDischargeM3s: 30,
    deficitPercent: 0,
    criticality: "Operational - KC Valley Reclaimed Route",
    description: "Handles storm runoff and KC Valley filling water discharge into local irrigation tanks.",
    lastDesilted: "2024-05-15"
  }
];

// Helper to convert drains into GeoJSON FeatureCollection with spatial properties
export function getKarnatakaDrainsGeoJSON(drains = KARNATAKA_DRAINS) {
  return {
    type: "FeatureCollection",
    features: drains.map(drain => ({
      type: "Feature",
      id: drain.id,
      geometry: {
        type: "Point",
        coordinates: drain.coordinates
      },
      properties: {
        id: drain.id,
        name: drain.name,
        shortName: drain.shortName,
        district: drain.district,
        taluk: drain.taluk,
        valley: drain.valley,
        type: drain.type,
        status: drain.currentStatus || drain.defaultStatus,
        designCapacityM3s: drain.designCapacityM3s,
        currentDischargeM3s: drain.currentDischargeM3s,
        deficitPercent: drain.deficitPercent,
        criticality: drain.criticality,
        description: drain.description,
        lastDesilted: drain.lastDesilted
      }
    }))
  };
}

// Bounding box of Karnataka state
export const KARNATAKA_BOUNDS = {
  center: [75.7139, 15.3173], // [lng, lat]
  zoom: 6.8,
  pitch: 35,
  bearing: 0,
  bbox: [[74.0, 11.5], [78.6, 18.5]]
};

// District regional centroids for multi-resolution cluster aggregation at state zoom
export const KARNATAKA_REGIONAL_CLUSTERS = [
  { region: "Bengaluru Metropolitan & Urban", district: "Bengaluru Urban", center: [77.63, 12.96], zoom: 12 },
  { region: "Mysuru & Mandya (Cauvery Basin)", district: "Mysuru", center: [76.75, 12.38], zoom: 11 },
  { region: "Coastal Karnataka (Mangaluru - Udupi)", district: "Dakshina Kannada", center: [74.78, 13.10], zoom: 11 },
  { region: "Uttara Kannada Coast & Ghats", district: "Uttara Kannada", center: [74.55, 14.50], zoom: 10.5 },
  { region: "Belagavi & Krishna-Ghataprabha", district: "Belagavi", center: [74.65, 15.95], zoom: 10.5 },
  { region: "Hubballi-Dharwad Twin Cities", district: "Dharwad", center: [75.08, 15.42], zoom: 11 },
  { region: "Kalaburagi & Kalyana Karnataka", district: "Kalaburagi", center: [77.10, 17.20], zoom: 10 },
  { region: "Ballari & Tungabhadra Basin", district: "Ballari", center: [76.65, 15.22], zoom: 10.5 },
  { region: "Central Karnataka (Shivamogga-Davanagere)", district: "Shivamogga", center: [75.75, 14.15], zoom: 10.5 },
  { region: "Western Ghats Headwaters (Kodagu-Hassan)", district: "Kodagu", center: [75.90, 12.70], zoom: 10.5 }
];
